// Local-only UI review. No application credentials or external API calls.
const fs=require('fs'),http=require('http');
const s=fs.readFileSync('jinsulmap/JINSUL_MAP_v3.5.7.html','utf8');
const functions=['scanDetailNumber','scanDetailMetric','scanDetailChartSection','scanRealtimeReport','scanVisitorDetail','scanFloatingDetail','scanRenderPopulationDetails','scanRenderPopulationDetailCharts','scanRenderVisitors','scanVisualBars','scanRenderFloatingBreakdown','scanEscapeHTML','scanCongestionTone','scanFormatPopulationRange','scanFormatDistance','scanReportTable','scanPeriodLabel','scanReportChart','scanSwitchReportTab'];
const js=functions.map(name=>s.match(new RegExp('^function '+name+'\\([^]*?^}','m'))[0]).join('\n');
const data={candidate:{isSeoul:true},population:{areaName:'왕십리역 · 검수용 모의 데이터',min:18000,max:20000,updateTime:'2026-09-07 16:00',distance:401,congestion:'보통',message:'화면 검수를 위한 예시입니다. 실제 API 수신값이 아닙니다.',ages:{0:2,10:8,20:27,30:24,40:15,50:12,60:8,70:4},femaleRate:52,maleRate:48,residentRate:20,nonResidentRate:80,forecast:[1,2,3,4,5,6].map((i)=>({time:'2026-09-07 '+(16+i)+':00',min:18000+i*1500,max:20000+i*1700,congestion:i>2?'약간 붐빔':'보통'}))},visitors:{region:'성동구',rows:['현지인','외지인','외국인'].flatMap((kind,i)=>['20260630','20260731'].map((date,j)=>({kind,date,value:Math.round((i===2?16000:210000)*(1+j*.18)),region:'성동구'}))),missingDates:['20260831']},commerce:{area:{name:'행당시장상점가'},floatingPeriod:'20262',floating:{total:855133,olderRate:28.5,peak:['17~21시'],breakdown:{times:[['00~06시',20000],['06~11시',160000],['11~14시',145000],['14~17시',170000],['17~21시',250000],['21~24시',110133]],days:['월','화','수','목','금','토','일'].map((d,i)=>[d,90000+i*10000]),ages:['10대','20대','30대','40대','50대','60대 이상'].map((a,i)=>[a,80000+i*20000])}}}};
const modal=s.slice(s.indexOf('<div class="modalBack" id="scanReportModal"'),s.indexOf('<div id="roadviewModal">'));
const page=`<!doctype html><meta charset="utf-8"><title>v3.5.7 UI 검수 · 모의 데이터</title><style>${s.match(/<style>([^]*?)<\/style>/)[1]}body{margin:0}#scanReportModal{display:flex}</style><script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>${modal}<script>const $=id=>document.getElementById(id),scanReportCharts={};const scanIsSeoulCandidate=c=>c.isSeoul;${js}\nconst fixture=${JSON.stringify(data)};scanRenderPopulationDetails(fixture);$('scanReportSubtitle').textContent='모의 데이터 · 서울 성동구 · 가독성/그래프 검수';$('scanReportKpis').innerHTML=scanDetailMetric('검수 화면','모의 데이터','실제 API 결과가 아닙니다');scanSwitchReportTab('population');setTimeout(()=>scanRenderPopulationDetailCharts(fixture),100);document.querySelectorAll('[data-scan-report-tab]').forEach(b=>b.onclick=()=>scanSwitchReportTab(b.dataset.scanReportTab));$('btnCloseScanReport').onclick=()=>{document.querySelector('.modalPanel').style.maxWidth=document.querySelector('.modalPanel').style.maxWidth?'':'540px'};</script>`;
http.createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});res.end(page)}).listen(8357,'127.0.0.1',()=>console.log('UI fixture preview at http://127.0.0.1:8357 (no API credentials)'));
