const scanSiteFields=[['title','자료 제목'],['unit','사용 층·호실'],['area','전용면적(평)','number'],['deposit','보증금(원)','number'],['rent','월세(원)','number'],['management','월 관리비(원)','number'],['premium','권리금(원)','number'],['vat','부가세 조건'],['available','입주 가능일'],['parking','실사용 주차·무료시간'],['elevator','승강기·휠체어 접근'],['visibility','간판·대로변 노출'],['layout','진료실·물리치료실·운동치료 공간'],['contact','현장 연락처 / 중개 담당'],['visitDate','임장일','date'],['notes','검토 메모']];
const scanSiteChecks=['주차장 진입·회차·환자 무료주차','입구 턱·휠체어·보행보조기 이동','승강기 크기·혼잡·정전 대안','간판 시인성·외벽/돌출간판 협의','진료실·물리치료실·운동치료실 동선','방음·바닥하중·전력·급배수 확인','영상장비 설치·차폐 검토 필요사항','약국 위치·횡단보도·버스/지하철 접근','건물 내 기존 의료기관·업종 제한','건축물 용도·의원 개설 가능 여부 확인','임대면적·관리비 항목·원상복구 협의','평일 오전·오후·토요일 보행 현장 관찰'];
const scanSite={drafts:new Map(),active:null,result:null,detailToken:0};
function scanSiteNum(v){if(v===null||v===undefined||String(v).trim()==='')return null;const n=Number(v);return Number.isFinite(n)&&n>=0?n:null;}
function scanSiteText(v){return String(v??'').slice(0,6000);}
function scanSiteEscape(v){return scanEscapeHTML(scanSiteText(v));}
function scanSiteRegionQuery(query){return !/[0-9]/.test(query)&&/^(?:[가-힣]+\s+){0,3}[가-힣]+(?:특별자치시|특별자치도|특별시|광역시|시|군|구|읍|면|동|리)$/.test(query.trim());}
function scanSiteKey(result){return [Number(result.candidate.lat).toFixed(6),Number(result.candidate.lng).toFixed(6),result.radiusMeters,result.candidate.searchScope||'site'].join(':');}
function scanSiteMoney(v){const n=scanSiteNum(v);return n===null?'미입력':n.toLocaleString('ko-KR')+'원';}
function scanSiteBudget(fields){const rent=scanSiteNum(fields.rent),management=scanSiteNum(fields.management),area=scanSiteNum(fields.area);return {monthly:rent===null||management===null?null:rent+management,areaM2:area===null?null:area*3.305785,perPyeong:rent===null||!area?null:rent/area};}
function scanSiteSameClinic(place,candidate){const norm=s=>String(s||'').replace(/\s/g,'');return norm(place.name)===norm(candidate.name)&&place.distance<=50;}
function scanSiteCompetition(result,exclude=true){
  const unavailable=!result.hira||result.hira.unavailable;
  const all=unavailable?[]:(result.hira.places||[]),excluded=exclude?all.filter(p=>scanSiteSameClinic(p,result.candidate)):[];
  const rows=all.filter(p=>!excluded.includes(p)).map(p=>({name:p.name,address:p.address,lat:p.lat,lng:p.lng,distance:p.distance,doctorCount:p.doctorCount,establishedDate:p.establishedDate,specialties:p.specialties,ykiho:p.ykiho}));
  const bins=[250,500,1000,Infinity].map((end,i)=>({label:i===0?'250m 이내':i===1?'250~500m':i===2?'500m~1km':'1km 초과',count:rows.filter(p=>p.distance<=(end)&&p.distance>(i?[250,500,1000][i-1]:-1)).length}));
  return {unavailable,partial:!!result.hira?.errorLabels?.length,excluded:excluded.length,rows,bins};
}
function scanSiteFacts(result){
  const rows=[],b=result.building,s=result.sgis,p=result.population,c=result.commerce,v=result.visitors;
  const add=(name,value,scope,when,source)=>rows.push({name,value,scope,when:when||'기준일 미표시',source});
  if(b&&!result.candidate.searchScope){for(const [name,value] of [['건물명',b.name],['지상 / 지하',(b.groundFloors??'-')+' / '+(b.undergroundFloors??'-')+'층'],['주용도',b.mainUse],['사용승인',scanFormatDate8(b.approvalDate)],['건물 전체 주차',b.parking+'대'],['승강기',b.elevators+'대']])add(name,value,'후보 필지 · 사용 호실과 구분','조회 '+result.createdAt?.slice(0,10),'건축물대장');}
  if(s)for(const [name,value,unit] of [['주거 인구',s.population,'명'],['종사자',s.employees,'명'],['가구',s.households,'가구'],['평균연령',s.avgAge,'세']])add(name,scanDetailNumber(value,unit),s.regionName,s.year?String(s.year)+'년':'연도는 SGIS 상세 참고','SGIS');
  if(p)add('실시간 추정인구',scanFormatPopulationRange(p.min,p.max),p.areaName+' 지정지점 · 반경 합계 아님',p.updateTime,'서울시');
  if(c?.floating)add('분기 유동인구',scanDetailNumber(c.floating.total,'명'),c.area.name+' 공식상권 전체',scanPeriodLabel(c.floatingPeriod),'서울시');
  if(v?.rows?.length){const latest=[...new Set(v.rows.map(r=>r.date))].sort().pop();for(const r of v.rows.filter(r=>r.date===latest))add('방문자 · '+r.kind,scanDetailNumber(r.value,'명'),v.region||result.candidate.sggName||'시군구 전체',latest,'한국관광공사');}
  if(!s)add('주거·종사자 인구','미연결 / 조회 실패','행정구역','현재 조회','SGIS');
  if(!p)add('실시간 추정인구',scanIsSeoulCandidate(result.candidate)?'미연결 / 지정지점 없음':'서울 밖 제공 범위 아님','서울 지정지점','현재 조회','서울시');
  if(!v?.rows?.length)add('방문자','자료 없음 / 미연결','시군구','현재 조회','한국관광공사');
  if(result.rone){const r=result.rone;add('임대료 참고',scanRoneMetricValue(r.latest.rent,1),r.selectedScope+' · '+r.propertyType,r.latest.rent?.period,'R-ONE · 개별 매물 월세 아님');add('공실률 참고',scanRoneMetricValue(r.latest.vacancy,1),r.selectedScope,r.latest.vacancy?.period,'R-ONE');}
  return rows;
}
function scanSiteClinicFact(result){
  const d=scanClinic.data;if(!d||!d.salesRows||scanClinic.key.split(':')[0]!==String(scanState.requestToken))return null;
  try{const code=scanClinic.industry,period=d.salesPeriod;const sale=scanClinicSales(scanClinicFind(d.salesRows,d.area.code,period,code));const store=scanClinicStore(scanClinicFind(d.stores[period]||[],d.area.code,period,code));if(!sale)return null;return {area:d.area.name,industry:scanClinicKinds[code],period:scanPeriodLabel(period),amount:sale.amount,stores:store?.total??null,perStore:sale.amount!==null&&store?.total>0?sale.amount/store.total:null};}catch{return null;}
}
function scanSiteSnapshot(result,draft){
  const competition=scanSiteCompetition(result,draft.exclude),candidate=result.candidate;
  return {candidate:{name:candidate.name,address:candidate.address,lat:candidate.lat,lng:candidate.lng,searchScope:candidate.searchScope||'',searchQuery:candidate.searchQuery||''},radius:result.radiusMeters,createdAt:result.createdAt,facts:scanSiteFacts(result),competition:{...competition,rows:competition.rows.map(({ykiho,...row})=>row)},clinic:scanSiteClinicFact(result),facilities:Object.values(result.facilities||{}).map(f=>({name:f.label,count:f.error?null:f.count,nearest:f.nearest?{name:f.nearest.name,lat:f.nearest.lat,lng:f.nearest.lng,distance:f.nearest.distance}:null,partial:!!f.truncated,error:!!f.error}))};
}
function scanSiteValidDraft(raw){
  if(!raw||raw.schema!=='jinsul-site-1'||!raw.snapshot?.candidate||typeof raw.key!=='string')throw Error('JINSUL 입지자료 JSON 파일이 아닙니다.');
  const c=raw.snapshot.candidate;if(!Number.isFinite(c.lat)||!Number.isFinite(c.lng)||Math.abs(c.lat)>90||Math.abs(c.lng)>180)throw Error('좌표가 올바르지 않습니다.');
  const fields={};for(const [key,,type] of scanSiteFields){fields[key]=scanSiteText(raw.fields?.[key]);if(type==='number'&&fields[key]!==''&&scanSiteNum(fields[key])===null)throw Error('금액·면적은 0 이상의 숫자로 입력해주세요.');}
  const photos={};for(const k of ['exterior','location']){const value=raw.photos?.[k]||'';if(value&&!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(value))throw Error('사진 형식이 올바르지 않습니다.');if(value.length>2500000)throw Error('사진 용량이 너무 큽니다.');photos[k]=value;}
  const snap=raw.snapshot,comp=snap.competition||{};
  const snapshot={candidate:{name:scanSiteText(c.name),address:scanSiteText(c.address),lat:c.lat,lng:c.lng,searchScope:scanSiteText(c.searchScope),searchQuery:scanSiteText(c.searchQuery)},radius:scanSiteNum(snap.radius)||1000,createdAt:scanSiteText(snap.createdAt),facts:(snap.facts||[]).slice(0,80).map(r=>Object.fromEntries(['name','value','scope','when','source'].map(k=>[k,scanSiteText(r[k])]))),competition:{unavailable:!!comp.unavailable,partial:!!comp.partial,excluded:scanSiteNum(comp.excluded)||0,rows:(comp.rows||[]).slice(0,1000).map(r=>({name:scanSiteText(r.name),address:scanSiteText(r.address),lat:scanSiteNum(r.lat),lng:scanSiteNum(r.lng),distance:scanSiteNum(r.distance),doctorCount:scanSiteNum(r.doctorCount),establishedDate:scanSiteText(r.establishedDate),specialties:(r.specialties||[]).slice(0,10).map(scanSiteText)}))},clinic:snap.clinic?{area:scanSiteText(snap.clinic.area),industry:scanSiteText(snap.clinic.industry),period:scanSiteText(snap.clinic.period),amount:scanSiteNum(snap.clinic.amount),stores:scanSiteNum(snap.clinic.stores),perStore:scanSiteNum(snap.clinic.perStore)}:null,facilities:(snap.facilities||[]).slice(0,10).map(r=>({name:scanSiteText(r.name),count:scanSiteNum(r.count),error:!!r.error,partial:!!r.partial,nearest:r.nearest?{name:scanSiteText(r.nearest.name),distance:scanSiteNum(r.nearest.distance),lat:scanSiteNum(r.nearest.lat),lng:scanSiteNum(r.nearest.lng)}:null}))};
  return {schema:'jinsul-site-1',key:raw.key.slice(0,180),fields,photos,exclude:raw.exclude!==false,checks:scanSiteChecks.map((_,i)=>['미확인','양호','확인 필요','해당 없음'].includes(raw.checks?.[i])?raw.checks[i]:'미확인'),snapshot,savedAt:scanSiteText(raw.savedAt)};
}
function scanSiteReadSaved(){try{const rows=JSON.parse(localStorage.getItem('jinsul.site.v1')||'[]');return Array.isArray(rows)?rows.map(r=>{try{return scanSiteValidDraft(r);}catch{return null;}}).filter(Boolean):[];}catch{return [];}}
function scanSiteOpen(){
  const result=scanState.result;if(!result)return;
  const key=scanSiteKey(result);let draft=scanSite.drafts.get(key)||scanSiteReadSaved().find(d=>d.key===key);
  if(!draft)draft={schema:'jinsul-site-1',key,fields:{title:result.candidate.name+' 입지자료'},photos:{},exclude:true,checks:scanSiteChecks.map(()=>'미확인')};
  scanSite.result=result;scanSite.active=draft;draft.snapshot=scanSiteSnapshot(result,draft);scanSite.drafts.set(key,draft);scanSiteRender();
}
function scanSiteSavedOptions(){return '<option value="">저장된 입지자료 선택</option>'+scanSiteReadSaved().map((d,i)=>'<option value="'+i+'">'+scanSiteEscape(d.fields.title||d.snapshot.candidate.address)+' · '+scanSiteEscape(d.savedAt.slice(0,10))+'</option>').join('');}
function scanSiteRender(){
  const d=scanSite.active;if(!d)return;const c=d.snapshot.candidate,regional=!!c.searchScope;
  $('scanSiteBody').innerHTML='<div class="siteIntro"><div><span class="siteEyebrow">FIELD NOTE · 정형외과 / 통증 / 재활</span><h3>개원 후보지 · 입지자료</h3><p>'+scanSiteEscape(c.address)+'</p></div><a class="btn outline" target="_blank" rel="noopener" href="'+scanSiteEscape(scanKakaoMapUrl(c))+'">지도·길찾기 ↗</a></div>'+(regional?'<div class="scanInsight warn">지역명 검색입니다. '+scanSiteEscape(c.searchQuery)+' 전체 분석이 아니라 대표 검색지점 주변 '+(d.snapshot.radius/1000)+'km 참고자료입니다. 임대 건물을 결정하려면 도로명주소·번지·건물명을 입력해 다시 스캔하세요. 대표지점의 건물을 임대 후보로 지정하지 않습니다.</div>':'')+(regional?'<section class="siteClinicBox"><h3>지역 내 임장 출발점</h3><p>검색된 정형외과 주변을 비교할 수 있습니다. 전체 의료기관 목록이나 추천 매물은 아닙니다.</p><button id="siteExplore" class="btn outline">지역 내 의료기관 주변 찾기</button><div id="siteExploreResults" role="status"></div></section>':'')+'<div class="siteActions"><button class="btn" id="siteSave">이 브라우저에 저장</button><button class="btn outline" id="siteRemove">저장본 삭제</button><button class="btn outline" id="siteJSON">자료 백업(JSON)</button><button class="btn outline" id="siteImport">자료 불러오기</button><button class="btn outline" id="siteHTML">입지자료 HTML 저장</button><button class="btn" id="sitePrint">A4 인쇄 / PDF</button><select class="scanSelect" id="siteSaved" aria-label="저장된 입지자료">'+scanSiteSavedOptions()+'</select></div><p id="siteStatus" role="status" class="scanCaption">현장 입력과 사진은 외부 서버로 보내지 않습니다. 브라우저 저장은 이 기기에만 보관되므로 JSON 백업을 권장합니다.</p><input id="siteImportFile" type="file" accept="application/json,.json" hidden><div class="siteWorkspace"><section class="siteEditor"><h4>임대조건 · 현장 확인</h4><p class="scanCaption">금액 단위: 원. 미입력은 0원이 아닙니다. 임대조건은 직접 확인한 값으로 작성하세요.</p><div class="siteFields">'+scanSiteFields.map(([key,label,type])=>'<label>'+label+(key==='notes'||key==='layout'?'<textarea data-site-field="'+key+'" rows="3">'+scanSiteEscape(d.fields[key])+'</textarea>':'<input data-site-field="'+key+'" type="'+(type||'text')+'" '+(type==='number'?'min="0" step="any"':'')+' value="'+scanSiteEscape(d.fields[key])+'">')+'</label>').join('')+'</div><div class="sitePhotoInputs"><label>외부·호실 사진<input id="sitePhotoExterior" type="file" accept="image/jpeg,image/png,image/webp"></label><button class="btn outline" id="siteClearExterior">외부 사진 제거</button><label>직접 확보한 위치·동선 이미지<input id="sitePhotoLocation" type="file" accept="image/jpeg,image/png,image/webp"></label><button class="btn outline" id="siteClearLocation">위치 이미지 제거</button></div><h4>임장 체크리스트</h4>'+scanSiteChecks.map((label,i)=>'<label class="siteCheck">'+label+'<select data-site-check="'+i+'">'+['미확인','양호','확인 필요','해당 없음'].map(s=>'<option'+(d.checks[i]===s?' selected':'')+'>'+s+'</option>').join('')+'</select></label>').join('')+'</section><section><div id="sitePreview"></div></section></div><section class="siteCompetition"><h3>경쟁의원 검토</h3><label class="siteExclude"><input id="siteExclude" type="checkbox" '+(d.exclude?'checked':'')+'> 후보지와 이름이 같고 50m 이내인 기존 의원을 이 비교에서 제외</label><div id="siteCompetitionBody"></div><div id="siteClinicContext"></div></section>';
  document.querySelectorAll('[data-site-field]').forEach(el=>el.oninput=()=>{d.fields[el.dataset.siteField]=el.value;scanSitePreview();});
  document.querySelectorAll('[data-site-check]').forEach(el=>el.onchange=()=>{d.checks[Number(el.dataset.siteCheck)]=el.value;scanSitePreview();});
  $('siteExclude').disabled=!scanSite.result;
  $('siteExclude').title=scanSite.result?'':'저장 당시 집계입니다. 제외 조건을 변경하려면 주소를 다시 스캔하세요.';
  $('siteExclude').onchange=e=>{d.exclude=e.target.checked;if(scanSite.result)d.snapshot=scanSiteSnapshot(scanSite.result,d);scanSitePreview();scanSiteRenderCompetition();};
  $('siteSave').onclick=scanSiteSave;$('siteRemove').onclick=()=>{try{localStorage.setItem('jinsul.site.v1',JSON.stringify(scanSiteReadSaved().filter(x=>x.key!==d.key)));$('siteSaved').innerHTML=scanSiteSavedOptions();scanSiteStatus('이 후보지의 브라우저 저장본을 삭제했습니다. 현재 편집 내용과 내려받은 파일은 유지됩니다.');}catch(e){scanSiteStatus('저장본 삭제 실패: '+e.message);}};$('siteJSON').onclick=()=>{try{const valid=scanSiteValidDraft(d);scanSiteDownload(JSON.stringify(valid,null,2),'application/json','json');}catch(e){scanSiteStatus(e.message);}};
  $('siteHTML').onclick=()=>{try{scanSiteDownload(scanSiteDocument(scanSiteValidDraft(d)),'text/html','html');}catch(e){scanSiteStatus(e.message);}};$('sitePrint').onclick=scanSitePrint;
  $('siteImport').onclick=()=>$('siteImportFile').click();$('siteImportFile').onchange=scanSiteImport;
  $('siteSaved').onchange=e=>{if(e.target.value==='')return;scanSite.active=scanSiteReadSaved()[Number(e.target.value)];scanSite.result=null;scanSiteRender();scanSiteStatus('저장 당시 자료를 불러왔습니다. 최신 API로 갱신하려면 해당 주소를 다시 스캔하세요.');};
  for(const [name,key] of [['Exterior','exterior'],['Location','location']]){$('sitePhoto'+name).onchange=e=>scanSitePhoto(e,key);$('siteClear'+name).onclick=()=>{d.photos[key]='';scanSitePreview();};}
  if($('siteExplore'))$('siteExplore').onclick=scanSiteExplore;
  scanSitePreview();scanSiteRenderCompetition();
}
function scanSiteStatus(message){if($('siteStatus'))$('siteStatus').textContent=message;}
function scanSiteSave(){try{const d=scanSiteValidDraft(scanSite.active);d.savedAt=new Date().toISOString();const rows=scanSiteReadSaved().filter(x=>x.key!==d.key);if(rows.length>=12)throw Error('저장본이 12개입니다. 기존 자료를 백업하고 선택해 저장본 삭제 후 다시 저장하세요.');rows.unshift(d);localStorage.setItem('jinsul.site.v1',JSON.stringify(rows));scanSite.active.savedAt=d.savedAt;$('siteSaved').innerHTML=scanSiteSavedOptions();scanSiteStatus('저장했습니다. 후보지 최대 12개 · '+d.savedAt.slice(0,16).replace('T',' ')+' UTC');}catch(e){scanSiteStatus('저장하지 못했습니다. '+e.message+' 사진이 크면 JSON 백업을 이용하세요.');}}
async function scanSiteImport(event){try{const file=event.target.files[0];if(!file)return;if(file.size>6500000)throw Error('자료 파일은 6.5MB 이하로 선택해주세요.');const d=scanSiteValidDraft(JSON.parse(await file.text()));scanSite.active=d;scanSite.result=null;scanSite.drafts.set(d.key,d);scanSiteRender();scanSiteStatus('파일의 저장 당시 자료를 불러왔습니다. 이 브라우저에 보관하려면 저장을 누르세요.');}catch(e){scanSiteStatus('불러오기 실패: '+e.message);}}
async function scanSitePhoto(event,key){const draft=scanSite.active;try{const file=event.target.files[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>16000000)throw Error('16MB 이하 JPG·PNG·WebP 사진을 선택해주세요.');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const factor=Math.min(1,1400/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*factor);canvas.height=Math.round(img.height*factor);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/jpeg',.8);if(data.length>2500000)throw Error('사진을 더 작은 크기로 선택해주세요.');draft.photos[key]=data;if(draft===scanSite.active)scanSitePreview();}finally{URL.revokeObjectURL(url);}}catch(e){scanSiteStatus(e.message);}}
function scanSiteDiagram(snapshot){
  const c=snapshot.candidate,radius=snapshot.radius||1000,places=snapshot.competition.rows.slice(0,18);const marks=places.filter(p=>Number.isFinite(p.lng)&&Number.isFinite(p.lat)).map((p,i)=>{const x=180+(p.lng-c.lng)*111320*Math.cos(c.lat*Math.PI/180)/radius*125,y=160-(p.lat-c.lat)*111320/radius*125;return '<circle cx="'+x.toFixed(1)+'" cy="'+y.toFixed(1)+'" r="7" fill="#be185d"/><text x="'+x.toFixed(1)+'" y="'+(y+3).toFixed(1)+'" text-anchor="middle" fill="white" font-size="8">'+(i+1)+'</text>';}).join('');
  return '<svg viewBox="0 0 360 325" role="img" aria-label="후보지 중심 경쟁의원 위치 개요"><rect width="360" height="325" rx="12" fill="#f1f5f9"/><circle cx="180" cy="160" r="125" fill="#e0f2fe" stroke="#0284c7" stroke-dasharray="5 5"/><path d="M180 25V295M45 160H315" stroke="#cbd5e1"/>'+marks+'<circle cx="180" cy="160" r="9" fill="#4338ca"/><text x="180" y="181" text-anchor="middle" font-size="12" fill="#312e81">후보 중심</text><text x="320" y="24" font-size="14">N ↑</text><text x="180" y="312" text-anchor="middle" font-size="11" fill="#475569">반경 '+radius+'m · 직선거리 개요 · 도로지도 아님</text></svg>';
}
function scanSiteSheet(d){
  const s=d.snapshot,c=s.candidate,f=d.fields,b=scanSiteBudget(f),e=scanSiteEscape;
  const table=rows=>'<table>'+rows.map(([label,value])=>'<tr><th>'+e(label)+'</th><td>'+e(value||'미입력')+'</td></tr>').join('')+'</table>';
  return '<article class="siteSheet"><header><span>JINSUL MAP · LOCATION BRIEF</span><h2>'+e(f.title||c.name+' 입지자료')+'</h2><p>'+e(c.address)+' '+e(f.unit)+'</p></header><div class="siteSheetGrid"><section><h3>외부·호실 사진</h3>'+(d.photos.exterior?'<img class="sitePhoto" src="'+d.photos.exterior+'" alt="사용자가 첨부한 외부 사진">':'<div class="sitePhotoEmpty">현장 사진을 첨부하세요</div>')+'<h3>위치·경쟁의원 개요</h3>'+(d.photos.location?'<img class="sitePhoto" src="'+d.photos.location+'" alt="사용자가 첨부한 위치 이미지">':scanSiteDiagram(s))+'<p class="siteFine">분홍 번호는 아래 경쟁의원 표의 가까운 순 번호입니다. 최대 18곳 표시.</p><a href="'+e(scanKakaoMapUrl(c))+'" target="_blank" rel="noopener">카카오 지도·길찾기 열기 ↗</a></section><section><h3>임대조건 · 사용자 확인값</h3>'+table([['주소',c.address],['층·호실',f.unit],['전용면적',f.area?f.area+'평 / 약 '+b.areaM2?.toFixed(2)+'㎡':''],['보증금',scanSiteMoney(f.deposit)],['월세',scanSiteMoney(f.rent)],['관리비',scanSiteMoney(f.management)],['월세 + 관리비',b.monthly===null?'미입력 항목 있음':scanSiteMoney(b.monthly)],['월세 / 전용평',b.perPyeong===null?'면적·월세 입력 필요':scanSiteMoney(Math.round(b.perPyeong))+'/평'],['부가세 조건',f.vat||'미확인 · 합계에 자동 가산하지 않음'],['권리금',scanSiteMoney(f.premium)],['입주 가능일',f.available],['실사용 주차',f.parking],['승강기·접근',f.elevator],['간판·노출',f.visibility],['치료 공간',f.layout],['연락처',f.contact],['임장일',f.visitDate]])+'</section></div><h3>공식 자료 · 기준 범위별 참고</h3>'+(c.searchScope?'<p class="siteWarning">지역명 검색: '+e(c.searchQuery)+'의 대표 검색지점 주변 '+s.radius+'m 자료입니다. 지역 전체 통계와 구분하며 개별 임대 후보 건물은 미지정입니다.</p>':'')+'<table><thead><tr><th>항목</th><th>값</th><th>공간 범위</th><th>기준·출처</th></tr></thead><tbody>'+s.facts.map(r=>'<tr><th>'+e(r.name)+'</th><td>'+e(r.value)+'</td><td>'+e(r.scope)+'</td><td>'+e(r.when)+' · '+e(r.source)+'</td></tr>').join('')+'</tbody></table>'+(!s.facts.length?'<p>공식 자료 없음. 미조회·실패 항목을 0으로 해석하지 않습니다.</p>':'')+'<h3>동선 · 임장 방문 포인트</h3>'+table(s.facilities.map(x=>[x.name,x.error?'조회 실패':(x.count??'자료 없음')+'곳'+(x.partial?' · 검색 일부 결과':'')+(x.nearest?' / 최근접 '+x.nearest.name+' '+Math.round(x.nearest.distance)+'m':'')]))+'<h3>현장 체크 · 정형외과 / 통증 / 재활</h3><div class="siteCheckPrint">'+scanSiteChecks.map((label,i)=>'<div><b>'+e(d.checks[i])+'</b> '+e(label)+'</div>').join('')+'</div><h3>검토 메모</h3><p class="siteMemo">'+e(f.notes||'미작성')+'</p><p class="siteFine">API 조회 '+e(s.createdAt?.replace('T',' ').slice(0,19))+' UTC · 건물 전체 주차와 임차인 실사용 주차는 다를 수 있습니다. 현장 적합성·의원 개설 가능 여부는 별도 확인 항목입니다.</p></article>';
}
function scanSiteCompetitionHTML(d){const s=d.snapshot,c=s.competition,e=scanSiteEscape;return '<h3>경쟁의원 비교 · 선택 진료과 / '+s.radius+'m</h3><p>'+ (c.unavailable?'심평원 조회 불가':c.rows.length+'곳'+(c.partial?' · 일부 진료과 조회 실패':''))+' · 동일 후보 의원 제외 '+c.excluded+'곳</p><table><thead><tr><th>#</th><th>의원 / 진료과</th><th>직선거리</th><th>신고 의사</th><th>개설일</th></tr></thead><tbody>'+c.rows.slice(0,60).map((p,i)=>'<tr><td>'+(i+1)+'</td><td>'+e(p.name)+'<small>'+e(p.specialties.join(', '))+'</small></td><td>'+Math.round(p.distance)+'m</td><td>'+e(p.doctorCount??'자료 없음')+'명</td><td>'+e(scanFormatHiraDate(p.establishedDate))+'</td></tr>').join('')+'</tbody></table>'+(c.rows.length>60?'<p>가까운 60곳 표시 / 전체 '+c.rows.length+'곳</p>':'')+'<p class="siteFine">출처: 심평원 신고 의원급 정보. 의사 수는 총 신고 의사 수이며 전문의 수·진료능력·매출 순위가 아닙니다. 조회 시점 현재 운영 목록이므로 폐업기관을 포함한 생존율을 계산하지 않습니다.</p>';}
function scanSiteClinicHTML(s){const c=s.clinic,e=scanSiteEscape;return c?'<div class="siteClinicBox"><h3>의원 업종 매출 · 경쟁 환경 참고</h3><p>'+e(c.area)+' · '+e(c.industry)+' · '+e(c.period)+'</p><div class="siteTriplet"><div>공식상권 추정매출<b>'+scanSiteMoney(c.amount)+'</b></div><div>동일 업종 점포<b>'+(c.stores??'자료 없음')+'곳</b></div><div>점포당 단순 나눗값<b>'+(c.perStore===null?'자료 없음':scanSiteMoney(Math.round(c.perStore)))+'</b></div></div><p class="siteFine">동일 상권·분기·업종의 금액 ÷ 점포 수입니다. 개별 경쟁병원의 실제 매출·예상 매출·손익분기점으로 사용하지 마세요. 반경의 심평원 의원 수로 나누지 않습니다. 출처: 서울시·서울신용보증재단.</p></div>':'<div class="siteClinicBox"><h3>의원 업종 매출</h3><p>서울 후보지는 ‘의원 업종’ 탭에서 공개 매출 조회를 완료한 뒤 이 탭을 다시 열면 포함됩니다. 서울 밖의 의원 매출은 현재 미연결입니다. 개별 경쟁병원 매출은 공개 자료로 확보되지 않았습니다.</p></div>';}
function scanSitePreview(){if($('sitePreview'))$('sitePreview').innerHTML=scanSiteSheet(scanSite.active);}
function scanSiteRenderCompetition(){
  const d=scanSite.active,c=d.snapshot.competition;$('siteCompetitionBody').innerHTML='<div class="siteChartBox"><canvas id="siteDistanceChart" role="img" aria-label="경쟁의원 거리 구간"></canvas></div>'+scanSiteCompetitionHTML(d)+(scanSite.result?'<div class="siteDetailButtons">'+c.rows.slice(0,20).map((p,i)=>'<button class="btn outline" data-site-detail="'+i+'">'+scanSiteEscape(p.name)+' 상세</button>').join('')+'<div id="siteHiraDetail" role="status"></div>':'');$('siteClinicContext').innerHTML=scanSiteClinicHTML(d.snapshot);
  const bins=[250,500,1000,Infinity].map((end,i)=>c.rows.filter(p=>p.distance<=end&&p.distance>(i?[250,500,1000][i-1]:-1)).length);
  scanReportChart('siteDistance','siteDistanceChart',{type:'bar',data:{labels:['250m 이내','250~500m','500m~1km','1km 초과'],datasets:[{label:'경쟁의원(곳)',data:c.unavailable?[null,null,null,null]:bins,backgroundColor:['#be185d','#7c3aed','#0284c7','#0f766e']}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},datalabels:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});
  document.querySelectorAll('[data-site-detail]').forEach(el=>el.onclick=()=>scanSiteDetail(Number(el.dataset.siteDetail)));
}
async function scanSiteDetail(index){
  if(!scanSite.result)return;const draft=scanSite.active,token=++scanSite.detailToken,p=scanSiteCompetition(scanSite.result,draft.exclude).rows[index],node=$('siteHiraDetail');if(!p)return;node.textContent=p.name+' 상세 조회 중…';
  try{const data=await scanFetchHiraDetails(p.ykiho);if(token!==scanSite.detailToken||draft!==scanSite.active)return;const d=data.detail||{},e=scanSiteEscape;const hours=[['월',d.trmtMonStart,d.trmtMonEnd],['화',d.trmtTueStart,d.trmtTueEnd],['수',d.trmtWedStart,d.trmtWedEnd],['목',d.trmtThuStart,d.trmtThuEnd],['금',d.trmtFriStart,d.trmtFriEnd],['토',d.trmtSatStart,d.trmtSatEnd]].map(([day,a,b])=>day+' '+(a||'미제공')+'~'+(b||'미제공')).join(' · ');node.innerHTML='<h4>'+e(p.name)+'</h4><p>'+e(hours)+'</p><p>주차 '+e(d.parkQty??'미제공')+' · '+e(d.parkEtc||'세부 안내 없음')+'</p><p>신고 진료과: '+e(data.departments.map(r=>r.dgsbjtCdNm).filter(Boolean).join(', ')||'미제공')+'</p><p>'+e(data.partial?'일부 상세 API 조회 실패 · 표시되지 않은 항목은 확인 필요':'심평원 상세 수신 · 실제 운영시간은 방문 전 확인')+'</p>';}catch(err){if(token===scanSite.detailToken&&draft===scanSite.active)node.textContent=p.name+' · '+scanApiErrorMessage(err);}
}
function scanSiteDownload(content,type,ext){const blob=new Blob([content],{type:type+';charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(scanSite.active.fields.title||'입지자료').replace(/[\\/:*?"<>|]/g,'_')+'.'+ext;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function scanSiteDocument(d){return '<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+scanSiteEscape(d.fields.title||'입지자료')+'</title><style>'+scanSiteExportCSS+'</style><body><nav class="printTools"><button onclick="window.print()">A4 인쇄 / PDF 저장</button><span>JINSUL MAP v3.5.9 · 저장 당시 자료</span></nav><main>'+scanSiteSheet(d)+'<section class="siteSheet sitePageBreak">'+scanSiteCompetitionHTML(d)+scanSiteClinicHTML(d.snapshot)+'</section></main></body></html>';}
function scanSitePrint(){try{const doc=scanSiteDocument(scanSiteValidDraft(scanSite.active));$('sitePrintFrame')?.remove();const frame=document.createElement('iframe');frame.id='sitePrintFrame';frame.title='입지자료 인쇄';frame.style.cssText='position:fixed;left:-10000px;width:794px;height:1123px;border:0';frame.onload=()=>{Promise.all(Array.from(frame.contentDocument.images,img=>img.decode().catch(()=>{}))).then(()=>{frame.contentWindow.focus();frame.contentWindow.print();});};frame.srcdoc=doc;document.body.appendChild(frame);scanSiteStatus('인쇄 대화상자를 요청했습니다. 앱에서 지원하지 않으면 HTML 저장 후 Edge·Chrome에서 인쇄하세요.');}catch(e){scanSiteStatus(e.message);}}
async function scanSiteExplore(){
  const d=scanSite.active,query=d.snapshot.candidate.searchQuery,node=$('siteExploreResults');if(!query||!node)return;node.textContent='지역 의료기관 검색 중…';
  try{const items=await new Promise((resolve,reject)=>places.keywordSearch(query+' 정형외과',(rows,status)=>status===kakao.maps.services.Status.OK?resolve(rows):status===kakao.maps.services.Status.ZERO_RESULT?resolve([]):reject(Error('지역 장소 검색에 실패했습니다.')),{size:15}));if(d!==scanSite.active)return;
  const city=query.split(/\s+/).find(t=>/(시|군|구)$/.test(t)&&!/(특별시|광역시)$/.test(t));const rows=items.filter(p=>!city||(p.address_name||'').includes(city));node.innerHTML=rows.length?rows.map((p,i)=>'<div class="siteExploreRow"><div><b>'+scanSiteEscape(p.place_name)+'</b><p>'+scanSiteEscape(p.road_address_name||p.address_name)+'</p></div><button class="btn outline" data-site-explore="'+i+'">이 주소 분석</button></div>').join(''):'해당 지역의 검색 결과가 없습니다. 동·역 이름 또는 구체적인 도로명주소로 검색해주세요.';
  node.querySelectorAll('[data-site-explore]').forEach(el=>el.onclick=()=>{const p=rows[Number(el.dataset.siteExplore)];$('scanAddress').value=p.road_address_name||p.address_name;$('scanReportModal').style.display='none';runMarketScan();});
  }catch(e){if(d===scanSite.active)node.textContent=e.message;}
}

const scanSiteExportCSS=`body{margin:0;background:#e8edf5;color:#172b49;font:14px/1.6 system-ui,'Malgun Gothic',sans-serif}*{box-sizing:border-box}main{max-width:1120px;margin:auto}a{color:#075985}button{padding:10px 20px;background:#4338ca;color:white;border:0;border-radius:8px}.printTools{max-width:1120px;margin:20px auto;display:flex;gap:20px;align-items:center}.siteSheet{background:white;padding:32px;margin:20px 0;border-radius:14px}.siteSheet header{border-bottom:3px solid #4338ca;margin-bottom:20px}.siteSheet header span{letter-spacing:2px;color:#4338ca;font-size:11px}.siteSheet h2{font-size:24px;margin:8px 0}.siteSheet h3{font-size:16px;margin:20px 0 10px;color:#243b68}.siteSheetGrid{display:grid;grid-template-columns:40% 1fr;gap:24px}.sitePhoto{width:100%;max-height:330px;object-fit:contain}.sitePhotoEmpty{min-height:220px;border:1px dashed #94a3b8;background:#f8fafc;display:grid;place-items:center;color:#475569}.siteSheet svg{width:100%;max-height:325px}.siteSheet table{border-collapse:collapse;width:100%;font-size:12px}.siteSheet th,.siteSheet td{border-bottom:1px solid #dbe3ef;text-align:left;padding:8px;overflow-wrap:anywhere}.siteSheet th{background:#f3f6fc;color:#334155}.siteSheet td small{display:block;color:#475569}.siteFine{font-size:11px;color:#475569}.siteWarning{padding:12px;background:#fff7ed;border-left:3px solid #c2410c}.siteMemo{white-space:pre-wrap}.siteCheckPrint{display:grid;grid-template-columns:1fr 1fr;gap:7px;font-size:12px}.siteCheckPrint b{color:#4338ca}.siteClinicBox{margin-top:20px;padding:20px;background:#f0f7ff;border:1px solid #c7d8f0;border-radius:12px}.siteTriplet{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.siteTriplet b{display:block;font-size:17px}.sitePageBreak{break-before:page}@media(max-width:700px){.siteSheetGrid,.siteTriplet,.siteCheckPrint{grid-template-columns:1fr}.siteSheet{padding:16px}.printTools{padding:12px}}@page{size:A4 portrait;margin:12mm}@media print{body{background:white;font-size:10pt}.printTools{display:none}.siteSheet{padding:0;margin:0;border-radius:0}.siteSheetGrid{grid-template-columns:38% 1fr;gap:12px}.siteSheet h2{font-size:17pt}.siteSheet h3{font-size:11pt}.siteSheet table,.siteFine{font-size:8pt}.siteSheet th,.siteSheet td{padding:5px}.siteSheet tr,.siteCheckPrint>div{break-inside:avoid}.sitePhoto{max-height:210px}.siteSheet svg{max-height:220px}.siteCheckPrint{grid-template-columns:1fr 1fr}thead{display:table-header-group}.siteClinicBox{break-inside:avoid}}`;
