// Offline browser rendering of actual authored controls with synthetic records/API.
const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('C:/Users/withe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const h=fs.readFileSync('jinsulmap/jinsulmap.html','utf8');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 const page=await browser.newPage({viewport:{width:1280,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.abort());
 const controls=h.slice(h.indexOf('<div id="patientImportMapping"'),h.indexOf('<div class="statGrid">',h.indexOf('<div id="patientImportMapping"')));
 await page.setContent('<html><head>'+[...h.matchAll(/<style[^>]*>[\s\S]*?<\/style>/g)].map(m=>m[0]).join('')+'</head><body><main style="padding:24px;max-width:1000px;margin:auto"><h1>합성 자료 · 주소 품질 검증</h1><p>실제 환자 파일과 API가 아닌 테스트 화면입니다.</p><section class="section">'+controls+'<div id="statTotalUsers"></div><div id="statTotalVisits"></div><button id="btnFit">범위 맞춤</button></section><p id="patientStatsStatus" role="status"></p></main></body></html>');
 await page.addScriptTag({content:`const $=id=>document.getElementById(id);let patients=[];const timer=window.setTimeout.bind(window);window.setTimeout=(f,ms)=>timer(f,Math.min(ms,60));const toggleState={new_only:true,new_conv:true,bit_90:true,old:true};const clusterer={clear(){}};const REP_COLOR={재진:'#1678aa'};const toast=()=>{};const patientStatsEscape=s=>String(s);const map={};const drawingManager={getData:()=>({circle:[]})};function applyFilter(){};class LatLng{constructor(y,x){this.y=y;this.x=x}}const kakao={maps:{LatLng,Marker:class{},MarkerImage:class{},Size:class{},InfoWindow:class{},event:{addListener(){}},services:{Status:{OK:'OK',ZERO_RESULT:'ZERO_RESULT'}}}};const geocoder={addressSearch(q,cb){timer(()=>{if(q.includes('실패로'))return cb([],'ERROR');if(q.includes('불일치로'))return cb([],'ZERO_RESULT');const r={x:'126.97',y:'37.56',address:{region_1depth_name:'서울특별시',region_2depth_name:'합성구',region_3depth_h_name:'합성동'}};cb(q.includes('다중로')?[r,{...r,x:'127.1'}]:[r],'OK');},5)}};`+h.slice(h.indexOf('function calcAgeFromRow('),h.indexOf('// ENTER on hospital input'))+h.slice(h.indexOf('let patientLoadToken=0;'),h.indexOf('function applyFilter(',h.indexOf('let patientLoadToken=0;')))});
 await page.evaluate(()=>parsePatients([['병원 주소 안내'],['환자번호','주소1','주소2','성명'],['000001','서울특별시 성동구','왕십리로 320','합성A'],['000002','서울특별시 성동구','왕십리로 320','합성B'],['000003','','','합성C'],['000004','서울특별시 성동구','','합성D'],['000005','서울특별시 성동구','불일치로 100','합성E'],['000006','서울특별시 성동구','실패로 100','합성F'],['000007','서울특별시 성동구','다중로 100','합성G'],['000008','경기도 시흥시 정왕대로 210','','합성H']]));
 await page.waitForFunction(()=>document.getElementById('patientAddressStatus').textContent.includes('처리 중 0'));
 const status=await page.locator('#patientAddressStatus').textContent();assert(status.includes('좌표 확인 3'));assert(status.includes('원주소 없음 1'));assert(status.includes('조회 실패 1'));assert(status.includes('다중 후보 1'));assert(status.includes('번지/건물번호 부족 1'));
 await page.addScriptTag({content:h.slice(h.indexOf('function patientAnalysisCircles('),h.indexOf('function buildVisiblePatients('))});
 await page.locator('summary').click();await page.locator('#patientStatsStatus').evaluate(el=>el.textContent=patientAddressStatisticsNote());await page.screenshot({path:'work/emr-address-desktop-v382.png',fullPage:true});
 await page.setViewportSize({width:768,height:1024});await page.screenshot({path:'work/emr-address-tablet-v382.png',fullPage:true});
 const boxes=await page.locator('#patientImportMapping select').evaluateAll(nodes=>nodes.map(el=>({height:el.getBoundingClientRect().height,right:el.getBoundingClientRect().right})));assert(boxes.every(b=>b.height>=44&&b.right<=768));assert.deepEqual(errors,[]);console.log('PASS actual controls offline synthetic:8people,3resolved,5separateunresolvedstates,manualmapping44px,desktop/tablet,noerrors');await browser.close();
})();
