const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const h=fs.readFileSync('jinsulmap/jinsulmap.html','utf8');
const fn=(name,next)=>h.slice(h.indexOf('function '+name+'('),h.indexOf('function '+next+'(',h.indexOf('function '+name+'(')));
const readers=[],parsed=[];class Reader{constructor(){readers.push(this)}readAsArrayBuffer(){}}
const c=vm.createContext({Uint8Array,TextDecoder,FileReader:Reader,toast(){},XLSX:{read:(s,o)=>{assert.equal(o.type,'string');assert(s.includes('차트번호,주소,성명'));return {Sheets:{s},SheetNames:['s']}},utils:{sheet_to_json:s=>s.split('\n').map(r=>r.split(','))}},window:{},patientFindHeader:()=>0,patientAddressSchema:()=>({bases:[1]}),window:{},patientFindHeader:()=>0,parsePatients:s=>parsed.push(s)});
vm.runInContext('let patientFileReadToken=0;'+h.slice(h.indexOf('async function processFile('),h.indexOf('let patientLoadToken=')),c);
(async()=>{for(const bytes of [Buffer.from('차트번호,주소,성명\n1,서울,테스트'),Buffer.from('c2f7c6aeb9f8c8a32cc1d6bcd22cbcbab8ed0a312cbcadbfef2cc5d7bdbac6ae','hex')]){await c.processFile({name:'synthetic.csv'});readers.at(-1).onload({target:{result:bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)}});}assert.equal(parsed.length,2);
const d=vm.createContext({scanEscapeHTML:s=>s,scanFormatDistance:n=>n+'m'});vm.runInContext(fn('scanComparisonFacilityLabel','scanRenderComparisons'),d);assert(d.scanComparisonFacilityLabel({label:'약국',error:true,count:0}).includes('조회 불가'));assert(!d.scanComparisonFacilityLabel({label:'약국',error:true,count:0}).includes('0곳'));assert(d.scanComparisonFacilityLabel({label:'약국',partial:true,count:2}).includes('확인 2곳 · 일부 미확인'));assert(d.scanComparisonFacilityLabel({label:'약국',count:0}).includes('0곳'));assert(d.scanComparisonFacilityLabel(null).includes('저장 자료 없음'));
require('./patient_audit_v380.cjs');
const ui={},p=vm.createContext({Map,Date,window:{},patients:[],patientLoadToken:0,$:id=>['patientImportMapping','patientAddressStatus','patientAddressRetry'].includes(id)?null:ui[id]||(ui[id]={}),toast(){},clusterer:{clear(){}},setTimeout(){},calcAgeFromRow:()=>null});vm.runInContext(fn('patientNewFlag','applyFilter'),p);p.parsePatients([['차트번호','주소','성명'],['A','서울','가'],['','서울','나'],['차트번호','주소','성명'],[],['A','서울','가']]);assert.equal(p.patients.length,1);assert.equal(p.patients[0].total,2);assert.deepEqual(JSON.parse(JSON.stringify(p.window.patientImportQuality)),{repeatedRows:1,sourceRows:4,acceptedRows:2,missingIdRows:1,headerRows:1});
assert(h.includes('window.patientImportQuality=null;window.__lastStatsVisible=[]'));assert(h.includes('PDF·인쇄: 첨부사진'));assert(h.includes('화면 로드뷰는 원문 링크로 출력'));assert(h.includes('max-width:900px'));assert(h.includes('.siteCheck select,.siteActions select{min-height:44px}'));console.log('PASS v381 UTF8/CP949 decoded headers, comparison failure/partial/zero, excluded-row accounting, reset/photo/tablet safeguards');})();
