/* Synthetic source/viewport tests; no network requests and no shared HTML edits. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {spawnSync}=require('node:child_process');
const {applyPatientCompetitionPatch}=require('./patch_patient_competition_v377.cjs');
const root=path.resolve(__dirname,'..');
const release=fs.readFileSync(path.join(root,'jinsulmap/jinsulmap.html'),'utf8');
const alreadyApplied=release.includes('function facilityCompetitionSearchScope(');
const html=alreadyApplied?release:applyPatientCompetitionPatch(release);
function fn(name){const start=html.indexOf('function '+name+'(');assert(start>=0,name);const end=html.indexOf('\n}',start)+2;return html.slice(start,end);}
const sourceStart=html.indexOf('const SENIOR_DIRECT_KEYWORDS =');
const sourceEnd=html.indexOf('\nfunction dedupPlacesByDistance',sourceStart);
let calls=[],response,current=true;
const c=vm.createContext({URL,Date,Math,Number,SCAN_SPECIALTY_ORDER:['정형외과','신경외과','마취통증의학과','재활의학과'],scanFetchHiraCompetition:async(...args)=>{calls.push(args);return response;}});
vm.runInContext(html.slice(sourceStart,sourceEnd)+'\n'+fn('scanHaversineMeters')+'\n'+fn('facilityCompetitionSearchScope')+'\n'+fn('facilityVerifiedClinicPlace')+'\n'+fn('facilityWithinBounds')+'\nasync '+fn('facilityFetchCompetition')+'\n'+fn('facilitySourceColumns'),c);
const bounds=(south,west,north,east)=>({getSouthWest:()=>({getLat:()=>south,getLng:()=>west}),getNorthEast:()=>({getLat:()=>north,getLng:()=>east})});
const b=bounds(37.49,126.99,37.51,127.01);
let checks=0;
const check=(actual,expected,message)=>{assert.deepEqual(JSON.parse(JSON.stringify(actual)),expected,message);checks++;};
const assessment={status:'competitor',reason:'선택 진료과 전문의 및 입원 병상 0개 확인',specialistCount:2,specialistCounts:{'정형외과':2},matchedSpecialties:['정형외과'],bedCount:0,checkedAt:'2026-09-30T00:00:00Z',criteriaVersion:'specialist-no-inpatient-v1'};
const clinic=(id,lat=37.5,lng=127,status='competitor')=>({ykiho:id,name:'검증 의원 '+id,address:'서울시 서초구 검증로 1',phone:'02-000-0000',lat,lng,competitionAssessment:{...assessment,status}});
(async()=>{
  const scope=c.facilityCompetitionSearchScope(b);
  check(scope.candidate,{lat:37.5,lng:127},'center derives from original map bounds');
  check(scope.radius>1000&&scope.radius<2000,true,'circle covers full viewport');
  for(const [lat,lng] of [[37.49,126.99],[37.49,127.01],[37.51,126.99],[37.51,127.01]])check(c.scanHaversineMeters(37.5,127,lat,lng)<=scope.radius,true,'corner stays within queried radius');
  assert.throws(()=>c.facilityCompetitionSearchScope(bounds(37.4,126.9,37.6,127.1)),/5km/);checks++;
  assert.throws(()=>c.facilityCompetitionSearchScope(bounds(NaN,127,38,128)),/범위/);checks++;
  const converted=c.facilityVerifiedClinicPlace(clinic('verified'));
  check([converted.place_name,converted.x,converted.y,converted.sourceProvider],['검증 의원 verified','127','37.5','hira']);
  check(c.facilityVerifiedClinicPlace(clinic('declaration',37.5,127,'declared')),null,'declarations never become confirmed facilities');
  check(c.facilityVerifiedClinicPlace({...clinic('missing'),competitionAssessment:null}),null,'legacy rows cannot become confirmed');
  check(c.facilityVerifiedClinicPlace({...clinic('bad'),lat:null}),null,'missing coordinates are rejected');
  const record=c.facilitySourceRecord(converted,'ortho',{retrievedAt:'later'});
  check(record.sourceProvider,'hira');
  check(record.facilityType,'경쟁의원');
  check(record.competitionAssessment,assessment,'classification evidence survives common source normalization');
  check(record.sourceRefs[0].recordId,'verified','HIRA provenance survives normalization');
  const columns=c.facilitySourceColumns(record);
  check([columns['출처'],columns['입원 병상(참고: 항목 최대값)'],columns['유관과 전문의(명)'],columns['분류 기준']],['건강보험심사평가원',0,2,'specialist-no-inpatient-v1']);
  check(columns['원문'],'https://www.data.go.kr/data/15001698/openapi.do');
  check(c.facilitySourceColumns({...record,competitionAssessment:{}})['입원 병상(참고: 항목 최대값)'],'미확인','missing evidence is never exported as zero');
  response={places:[],competitors:[clinic('in'),clinic('border',37.49,126.99),clinic('out',37.52,127),clinic('wrong-status',37.5,127,'unverified')],declared:[clinic('declared',37.5,127,'declared')],unverified:[clinic('unknown',37.5,127,'unverified'),clinic('outside-unknown',37.52,127,'unverified')],excluded:[clinic('beds',37.5,127,'excluded')],errorLabels:['재활의학과']};
  const result=await c.facilityFetchCompetition(b,()=>current);
  check(result.places.map(p=>p.id),['in','border'],'only canonical verified rows inside original viewport are returned');
  check([result.declaredCount,result.unverifiedCount,result.excludedCount,result.partial],[1,1,1,true]);
  check(calls[0][0],['정형외과','신경외과','마취통증의학과','재활의학과']);
  check(calls[0][3],0);
  check(typeof calls[0][4],'function','patient request callback is sent separately from commercial scan token');
  current=false;
  check(await c.facilityFetchCompetition(b,()=>current),{cancelled:true},'stale response cannot publish facilities');
  current=true;
  const before=calls.length;
  await assert.rejects(()=>c.facilityFetchCompetition(bounds(37.4,126.9,37.6,127.1),()=>current),/5km/);checks++;
  check(calls.length,before,'oversized viewport never makes truncated HIRA query');
  response={places:[],competitors:[],declared:[],unverified:[],excluded:[],unavailable:true,errorLabels:['전체']};
  check((await c.facilityFetchCompetition(b,()=>current)).unavailable,true,'unavailable result retains failure state');
  const handler=html.slice(html.indexOf("$('btnSearch').onclick = async () => {"),html.indexOf("$('btnResetSearch').onclick"));
  check(handler.includes("else if (t === 'ortho') { imageSrc = SVG_MARKERS.ortho; }"),true,'ortho has no Kakao keyword array');
  check(handler.includes('facilityFetchCompetition(bounds,()=>requestToken===facilitySearchRequestToken)'),true);
  check(handler.includes('0곳을 의미하지 않음'),true);
  for(const script of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))if(script[1].trim())new vm.Script(script[1]);
  checks++;
  // Run the existing senior/route/export tests against the in-memory transformed HTML.
  const runner=String.raw`const fs=require('node:fs'),path=require('node:path'),Module=require('node:module');const filename=path.resolve('work/test_senior_current.cjs');let source=fs.readFileSync(filename,'utf8');source=source.replace("const html = fs.readFileSync(path.resolve(__dirname, '../jinsulmap/jinsulmap.html'), 'utf8');","const rawHtml = fs.readFileSync(path.resolve(__dirname, '../jinsulmap/jinsulmap.html'), 'utf8'); const html = rawHtml.includes('function facilityCompetitionSearchScope(') ? rawHtml : require('./patch_patient_competition_v377.cjs').applyPatientCompetitionPatch(rawHtml);");const m=new Module(filename,module);m.filename=filename;m.paths=Module._nodeModulePaths(path.dirname(filename));m._compile(source,filename);`;
  const senior=spawnSync(process.execPath,['-e',runner],{cwd:root,encoding:'utf8'});
  if(senior.status!==0)throw Error('Existing senior regression failed: '+senior.stderr+' '+senior.stdout);
  console.log(JSON.stringify({ok:true,checks,liveApi:false,input:alreadyApplied?'already-applied HTML':'in-memory patch',seniorRegression:senior.stdout.trim(),testEditedSharedHtml:false}));
})().catch(error=>{console.error(error);process.exitCode=1;});
