/* Release-HTML regression tests: one observed Kakao result name + synthetic edges. No live API calls. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const dir=__dirname;
const release=fs.readFileSync(path.join(dir,'../jinsulmap/jinsulmap.html'),'utf8');
const sourceStart=release.indexOf('function seniorFacilityDetails(');
const sourceEnd=release.indexOf('\nfunction seniorNormalizedText',sourceStart);
assert.ok(sourceStart>=0&&sourceEnd>sourceStart,'release HTML must contain the integrated shelter/source helpers before seniorNormalizedText');
const source=release.slice(sourceStart,sourceEnd);
for(const name of ['seniorFacilityDetails','seniorFacilityKind','facilityDistrictQuery','facilityMapSearchQuery','facilitySafeHttpUrl','facilitySourceRecord'])assert.ok(source.includes('function '+name+'('),'release helper missing: '+name);
const ctx={URL};vm.createContext(ctx);vm.runInContext(source,ctx);
let checks=0;
const check=(actual,expected,message)=>{assert.deepEqual(JSON.parse(JSON.stringify(actual)),expected,message);checks++;};
const base={place_name:'무더위,한파쉼터 부산이동(플랫폼)노동자지원센터해운대센터',address_name:'부산 해운대구 구남로29번길 38',id:'529000628',x:'129.1600',y:'35.1610',place_url:'http://place.map.kakao.com/529000628'};
check(ctx.seniorFacilityKind(base),'direct','combined cooling/cold shelter prefix retained');
check(ctx.seniorFacilityDetails(base).facilityType,'냉방쉼터');
check(ctx.seniorFacilityDetails(base).isSeniorFacility,null,'worker shelter must not be presented as senior center');
for(const name of ['무더위·한파쉼터 시민센터','무더위/한파쉼터(은행)','한파·무더위쉼터 시민센터','폭염 쉼터 중앙도서관','중앙도서관 무더위,한파쉼터'])check(ctx.seniorFacilityKind({place_name:name}),'direct',name);
for(const name of ['무더위쉼터카페','무더위,한파쉼터식당','경로당식당','한파쉼터 문화센터'])check(ctx.seniorFacilityKind({place_name:name}),'unclassified',name);
check(ctx.seniorFacilityDetails({place_name:'무더위쉼터 매봉경로당'}).isSeniorFacility,true);
check(ctx.seniorFacilityDetails({place_name:'마을회관'}).isSeniorFacility,null);
check(ctx.seniorFacilityDetails({place_name:'늘푸른센터',category_name:'사회 > 경로당,노인정'}).isSeniorFacility,true,'retain combined category support');
check(ctx.seniorFacilityDetails({place_name:'시민도서관',sourceProvider:'official',officialShelter:true}).designationStatus,'공공자료 지정');
check(ctx.seniorFacilityKind({place_name:'시민도서관',officialShelter:true}),'unclassified','untrusted or unidentified provider must not assert official designation');
check(ctx.seniorFacilityKind({place_name:'한일아파트 경비실'}),'auxiliary');
check(ctx.facilityDistrictQuery('경기 용인시 처인구 금어로 46 101호'),'경기 용인시 처인구');
check(ctx.facilityDistrictQuery('서울특별시 성동구 왕십리로 1 3층'),'서울특별시 성동구');
check(ctx.facilityDistrictQuery('세종특별자치시 한누리대로 2130'),'세종특별자치시');
check(ctx.facilityDistrictQuery('신흥로 197'),'');
check(ctx.facilityMapSearchQuery({place_name:'중앙경로당',road_address_name:'경기 시흥시 정왕대로 74 101호'}),'경기 시흥시 중앙경로당');
const row=ctx.facilitySourceRecord(base,'senior',{retrievedAt:'2026-09-29T00:00:00Z'});
check(row.id,'kakao:529000628');
check(row.sourceUrl,base.place_url);
check(row.mapLinks.kakao,'https://place.map.kakao.com/529000628');
check(row.comparisonStatus,'대조 미확인','creating links does not verify search result');
check(row.sourceRefs.length,1);
check(row.retrievedAt,'2026-09-29T00:00:00Z');
check(row.recordDate,'','lookup date must not become source record date');
check(row.validCoordinates,true);
check(ctx.facilitySourceRecord({...base,sourceProvider:'official',officialShelter:true}).id==='kakao:529000628',false,'provider IDs do not collide');
check(ctx.facilitySourceRecord({...base,y:''}).validCoordinates,false,'missing latitude is not numeric zero');
check(ctx.facilitySourceRecord({...base,x:'181'}).validCoordinates,false);
check(ctx.facilitySourceRecord({...base,place_url:'javascript:alert(1)'}).sourceUrl,'');
check(ctx.facilitySourceRecord({...base,sourceProvider:'official',officialShelter:true,sourceUrl:'https://example.gov.kr/shelters',recordDate:'2026-06-01'}).mapLinks.official,'https://example.gov.kr/shelters');
check(ctx.facilitySourceRecord({...base,sourceRefs:[{provider:'official',sourceUrl:'https://example.gov.kr/list',recordDate:'2026-06-01'}]}).sourceRefs.length,2,'existing official evidence preserved alongside place source');
check(row.mapLinks.naver.includes(encodeURIComponent('부산 해운대구 ')),true,'NAVER query includes district');
check(row.mapLinks.naver.includes(encodeURIComponent('구남로29번길')),false,'NAVER query excludes overlong street/unit');
console.log(JSON.stringify({ok:true,checks,source:'release HTML',liveApi:false,observedNameFixture:'Kakao API comparison 2026-09-29',mainHtmlModified:false}));
