const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');const h=fs.readFileSync('jinsulmap/jinsulmap.html','utf8');
function fn(name){let a=h.indexOf('function '+name+'(');if(h.slice(a-6,a)==='async ')a-=6;return h.slice(a,h.indexOf('\n}',a)+2);}
const configs={};const c=vm.createContext({Map,Date,Number,URLSearchParams,SEOUL_SALES_BY_AREA:new Map(),SEOUL_COMMERCE_SALES_PERIOD:'2026Q1',scanFloatingBreakdown:()=>({}),scanReportChart:(key,id,config)=>configs[key]=config,scanRenderRoneChart:()=>{},scanRenderPopulationDetailCharts:()=>{}});
vm.runInContext(['scanNumber','scanPick','scanBuildCommerceData','scanRenderReportCharts','scanReportScores','scanEscapeHTML','scanRoneMetricValue','scanMedian'].map(fn).join('\n'),c);
let data=c.scanBuildCommerceData({code:'A'},[{TRDAR_CD:'A',TOT_FLPOP_CO:100,AGRDE_50_FLPOP_CO:20}],[]);assert.equal(data.floating.olderRate,null);assert.equal(data.floating.male,null);
data=c.scanBuildCommerceData({code:'A'},[{TRDAR_CD:'A',TOT_FLPOP_CO:100,AGRDE_50_FLPOP_CO:20,AGRDE_60_ABOVE_FLPOP_CO:30}],[{}]);assert.equal(data.floating.olderRate,50);assert.equal(data.stores.count,null);
data=c.scanBuildCommerceData({code:'A'},[{TRDAR_CD:'A',TOT_FLPOP_CO:0,AGRDE_50_FLPOP_CO:0,AGRDE_60_ABOVE_FLPOP_CO:0}],[]);assert.equal(data.floating.total,0);assert.equal(data.floating.olderRate,null);
c.scanRenderReportCharts({specialties:[{name:'A',count:0,error:true},{name:'B',count:0,error:false}],facilities:{a:{label:'A',count:0,error:true}}},{scores:[]});assert.equal(configs.competition.data.datasets[0].data[0],null);assert.equal(configs.competition.data.datasets[0].data[1],0);assert.equal(configs.facility.data.datasets[0].data[0],null);assert.equal(c.scanReportScores({}).total,null);
assert.equal(c.scanMedian([0,100,200,300,null]),150);assert(c.scanRoneMetricValue({value:-1.2,unit:'%',period:'2026Q2'}).includes('-1.2'));assert(c.scanRoneMetricValue({value:-1.2,unit:'%',period:'2026Q2'}).includes('2026Q2'));
console.log('PASS source missing versus zero, age-share denominator, failed series, median, signed return with period, score removal');
const {chromium}=require('C:/Users/withe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const page=await browser.newPage();
await page.setContent('<div style="height:350px"><canvas id="fallback"></canvas></div>');await page.addScriptTag({content:'const $=id=>document.getElementById(id);const scanReportCharts={};'+['scanEscapeHTML','scanReportTable','scanReportChart'].map(fn).join('\n')});
await page.evaluate(()=>scanReportChart('test','fallback',{data:{labels:['negative','zero','missing'],datasets:[{label:'투자수익률(%)',data:[-1.2,0,null]}]}}));const text=await page.locator('.scanChartFallback').innerText();assert(text.includes('-1.2'));assert(text.includes('자료 없음'));assert(text.includes('zero\t0'));await page.screenshot({path:'work/audit-fallback-v371.png'});await browser.close();console.log('PASS browser no-CDN fallback keeps negatives, zero and missing distinct');})().catch(e=>{console.error(e.stack);process.exitCode=1});
