const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const results=[];
function env(extra={}){const c=vm.createContext({URL,AbortController,Date,Map,Set,document:{getElementById:()=>null},setTimeout:(f,n)=>setTimeout(f,n>=30000?n===30000?8:30:1),clearTimeout,scanApiErrorMessage:e=>e.message||e.name,...extra});vm.runInContext(fs.readFileSync('work/network_v355.js','utf8'),c);return c;}
async function test(name,f){try{await f();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.message});}}
(async()=>{
await test('slow first attempt recovers with longer second deadline',async()=>{let calls=0;const c=env({fetch:(u,{signal})=>new Promise((resolve,reject)=>{calls++;signal.addEventListener('abort',()=>{const e=Error('timeout');e.name='AbortError';reject(e)});setTimeout(()=>resolve({ok:true,text:async()=>'ok'}),15);})});assert.equal(await c.scanNetworkRequest('https://example.test'), 'ok');assert.equal(calls,2);assert.equal(vm.runInContext('scanNetwork.metrics[0].status',c),'시간 초과');});
await test('response body timeout remains covered',async()=>{const c=env({fetch:async(u,{signal})=>({ok:true,text:()=>new Promise((r,j)=>signal.addEventListener('abort',()=>{const e=Error('body timeout');e.name='AbortError';j(e)}))})});await assert.rejects(c.scanNetworkRequest('https://example.test'),/재시도/);});
await test('403 has no automatic retry',async()=>{let calls=0;const c=env({fetch:async()=>{calls++;return {ok:false,status:403}}});await assert.rejects(c.scanNetworkRequest('https://example.test/?secret=hidden'),/403/);assert.equal(calls,1);assert.ok(!JSON.stringify(vm.runInContext('scanNetwork.metrics',c)).includes('secret'));});
await test('503 recovers once',async()=>{let calls=0;const c=env({fetch:async()=>++calls===1?{ok:false,status:503}:{ok:true,text:async()=>'ok'}});assert.equal(await c.scanNetworkRequest('https://example.test'),'ok');assert.equal(calls,2);});
await test('HTTP 200 upstream timeout code retries',async()=>{let calls=0;const c=env({fetch:async()=>({ok:true,text:async()=>++calls===1?JSON.stringify({response:{header:{resultCode:'05'}}}):'ok'})});assert.equal(await c.scanNetworkRequest('https://example.test'),'ok');assert.equal(calls,2);});
await test('daily quota code does not retry',async()=>{let calls=0;const c=env({fetch:async()=>({ok:true,text:async()=>{calls++;return '<resultCode>22</resultCode>';}})});await c.scanNetworkRequest('https://example.test');assert.equal(calls,1);});
await test('family concurrency is capped and queued calls complete',async()=>{let active=0,max=0;const c=env({fetch:async()=>{max=Math.max(max,++active);await new Promise(r=>setTimeout(r,2));active--;return {ok:true,text:async()=>'ok'}}});await Promise.all(Array.from({length:6},()=>c.scanNetworkRequest('https://example.test')));assert.equal(max,2);assert.equal(vm.runInContext('scanNetwork.metrics.length',c),6);});
await test('cancel aborts active and queued calls without retry',async()=>{let calls=0;const c=env({fetch:(u,{signal})=>new Promise((r,j)=>{calls++;signal.addEventListener('abort',()=>{const e=Error('cancel');e.name='AbortError';j(e)});})});const work=Promise.allSettled(Array.from({length:4},()=>c.scanNetworkRequest('https://example.test')));setTimeout(()=>c.scanCancelNetwork(),2);const r=await work;assert.ok(r.every(x=>x.status==='rejected'));assert.equal(calls,2);});
const c=vm.createContext({Date,Map,Set,URLSearchParams,PUBLIC_DATA_API_KEY:'fixture',scanNumber:v=>Number(String(v).replaceAll(',','')),scanState:{requestToken:1},scanApiErrorMessage:e=>e.message});vm.runInContext(fs.readFileSync('work/visitors_v355.js','utf8'),c);
await test('nationwide rows match legal district and exact day only',()=>{const r=c.scanVisitorSelect([{signguCode:'26350',baseYmd:'20260831',touNum:'1,234',touDivNm:'외지인'},{signguCode:'11110',baseYmd:'20260831',touNum:'99'}],{legalCode:'2635010600'},'20260831');assert.equal(r.length,1);assert.equal(r[0].value,1234);});
await test('missing visitor metric is not zero',()=>{assert.equal(c.scanVisitorSelect([{signguCode:'26350',baseYmd:'20260831'}],{legalCode:'2635010600'},'20260831')[0].value,null);});
await test('month-end dates handle year rollover and leap day',()=>{assert.deepEqual(Array.from(c.scanVisitorDates(new Date(2024,2,3))),['20240229','20240131','20231231']);});
await test('authorization failure stops extra date requests',async()=>{let calls=0;c.scanVisitorDay=async()=>{calls++;throw Error('승인 필요')};await c.scanPrepareVisitors({legalCode:'2635010600'},1);assert.equal(calls,1);assert.equal(c.scanState.visitors.status,'error');});
console.log(JSON.stringify({passed:results.filter(r=>r.status==='PASS').length,total:results.length,results},null,2));fs.writeFileSync('work/network-test-results-v355.json',JSON.stringify(results,null,2));if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
})();
