const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');const src=fs.readFileSync('work/banner_client_v379.js','utf8');const sandbox={console,URL,AbortSignal,TextDecoder,Date,document:{getElementById:()=>({textContent:''})},location:{href:'https://jinsul-lab.github.io/statistics-lab/jinsulmap/jinsulmap.html'},window:{},fetch:global.fetch};vm.createContext(sandbox);vm.runInContext('let bannerPointsCache=null;'+src,sandbox);let n=0;function check(v){assert(v);n++}
(async()=>{
 const csv=new TextDecoder('euc-kr').decode(fs.readFileSync('jinsulmap/banner_2026-01-22.csv'));const rows=sandbox.parseBannerCsv(csv),norm=sandbox.normalizeBannerRows(rows);check(rows.length===7305);check(norm.points.length>7000);check(norm.points[0].addr.length>0);check(sandbox.parseBannerCsv('위도,경도,게시대명\r\n37,127,"a\n""b"""')[0]['게시대명']==='a\n"b"');check(sandbox.normalizeBannerRows([{lat:'',lot:''},{lat:91,lot:127}]).invalid===2);check(sandbox.normalizeBannerRows([rows[0],rows[0]]).duplicates===1);
 const pages=[];const first=await sandbox.fetchBannerPage(1);pages.push(first);for(let p=2;p<=Math.ceil(first.totalCount/1000);p++)pages.push(await sandbox.fetchBannerPage(p));const live=pages.flatMap(p=>p.items);check(live.length===8331);check(pages.every(p=>p.totalCount===first.totalCount));const liveNorm=sandbox.normalizeBannerRows(live);check(liveNorm.duplicates===0);
 sandbox.fetch=async()=>({ok:false,status:500});const failed=await sandbox.loadBannerPoints();check(failed===null);check(await sandbox.loadBannerPoints()===null);
 let requests=0;sandbox.fetch=async u=>{requests++;if(String(u).includes('workers.dev'))return {ok:false,status:504};return {ok:true,arrayBuffer:async()=>fs.readFileSync('jinsulmap/banner_2026-01-22.csv')}};check((await sandbox.loadBannerPoints()).length===norm.points.length);check(requests===2);
 const scripts=[...fs.readFileSync('jinsulmap/jinsulmap.html','utf8').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(x=>x[1]).filter(Boolean);for(const script of scripts)new vm.Script(script);check(scripts.length>0);
 const result={checks:n,csv:{rows:rows.length,valid:norm.points.length,invalid:norm.invalid,duplicates:norm.duplicates},api:{rows:live.length,valid:liveNorm.points.length,invalid:liveNorm.invalid,duplicates:liveNorm.duplicates,pages:pages.length},date:new Date().toISOString()};fs.writeFileSync('work/banner-results-v379.json',JSON.stringify(result,null,2));console.log(result);
})().catch(e=>{console.error(e.message);process.exitCode=1});
